### ISSUE TITLE
`perspective-exwm-switch-perspective` doesn't work properly if the current workspace has a floating window

### ISSUE THREAD

**Issue by NickRaleigh** [SqrtMinusOne/perspective-exwm.el#2]
I've been really enjoying this package so far. One little bug I've noticed is if I use `perspective-exwm-switch-perspective` while the current workspace has a floating window, after I make a selection, the workspace flickers and stays on the  current perspective. I believe it may be a bug with `exwm-workspace-switch`, so there might not be a viable solution.

**Comment by SqrtMinusOne** [comment]
Wrapping the call to `exwm-workspace-switch` in `exwm--defer` seems to have fixed it (https://github.com/SqrtMinusOne/perspective-exwm.el/commit/c320f0967db3ae2d49081f669e1f424a21a354fb).

Somehow `exwm-input--update-focus` made a deferred call to `exwm-workspace-switch` that switched to the original frame if the switch originated from the minibuffer. And the mechanism of that remains arcane for me.
